### ISSUE TITLE
How clustering is done

### ISSUE THREAD

**Issue by SirVizzy** [vitali-fedulov/similar.pictures#4]
I'm wondering how the clustering algorithm works in the provided demo. I cannot see it as the code has been obfuscated. I'd like to create the clusters in the exact same way.

**Comment by vitali-fedulov** [comment]
When image A is similar to image B I check if there is a cluster X where either A or B was previously added and add either A or B to this cluster, depending which one was not already in the cluster.

If there is no cluster where either A or B is present I create a new cluster Y and add both A and B into the cluster.

I add A or B to only one cluster, because there might be situations when an image could be placed in several clusters. So the method assumes there are no "bridges" between clusters in N-dimensional space, meaning clusters are well separated between each other in the space.

**Comment by SirVizzy** [comment]
Thank you, I was kind of able to figure out how it works de-obfuscating the provided JavaScript. Thanks for the clarification. Will close this now.
